///////////////////////////////// Screens PushNamed Names/////////////////////////////////////////////

// ignore_for_file: constant_identifier_names

//USER
const REGISTER_SCREEN_R = 'REGISTER_SCREEN_R';
const LOGIN_SCREEN_R = 'LOGIN_SCREEN_R';
const VERIFICATION_SCREEN_R = 'VERIFICATION_SCREEN_R';
const HOME_LAYOUT_R = 'HOME_LAYOUT_R';
const HOME_SCREEN_R = 'HOME_SCREEN_R';
const PROFILE_SCREEN_R = 'PROFILE_SCREEN_R';
const ORDERS_SCREEN_R = 'ORDERS_SCREEN_R';
const FAVOURITES_SCREEN_R = 'FAVOURITES_SCREEN_R';
const TRACKING_ORDER_SCREEN_R = 'TRACKING_ORDER_SCREEN_R';
const ABOUT_SCREEN_R = 'ABOUT_SCREEN_R';
const FREQUENTLY_ASKED_QUESTIONS_SCREEN_R = 'FREQUENTLY_ASKED_QUESTIONS_SCREEN_R';
const POLICY_AND_TERMS_SCREEN_R = 'POLICY_AND_TERMS_SCREEN_R';
const LANGUAGE_SCREEN_R = 'LANGUAGE_SCREEN_R';
const NOTIFICATIONS_SCREEN_R = 'NOTIFICATIONS_SCREEN_R';
const DELIVERY_INFORMATION_SCREEN_R = 'DELIVERY_INFORMATION_SCREEN_R';
const CART_SCREEN_R = 'CART_SCREEN_R';
const OFFERS_SCREEN_R = 'OFFERS_SCREEN_R';
const FILTER_SCREEN_R = 'FILTER_SCREEN_R';
const WALLET_SCREEN_R = 'WALLET_SCREEN_R';
const CATEGORIES_SCREEN_R = 'CATEGORIES_SCREEN_R';
const PRODUCTS_IN_STOCK_SCREEN_R = 'PRODUCTS_IN_STOCK_SCREEN_R';
const ADDING_PRODUCT_TO_CART_SCREEN_R = 'ADDING_PRODUCT_TO_CART_SCREEN_R';
const DELIVERY_LOCATION_SCREEN_R = 'DELIVERY_LOCATION_SCREEN_R';
const PAYMENT_METHOD_SCREEN_R = 'PAYMENT_METHOD_SCREEN_R';
const QR_CODE_SCREEN_R = 'QR_CODE_SCREEN_R';
const DELIVERY_DETAILS_SCREEN_R = 'DELIVERY_DETAILS_SCREEN_R';
const USER_ADDRESSES_SCREEN_R = 'USER_ADDRESSES_SCREEN_R';
const ADDING_ADDITIONAL_LOCATION_SCREEN_R = 'ADDING_ADDITIONAL_LOCATION_SCREEN_R';
const SEARCH_SCREEN_R = 'SEARCH_SCREEN_R';

