enum SharedPreferencesKeys {
  SP_APP_LANGUAGE,
  SP_API_TOKEN_KEY,
  SP_GOOGLE_ACCESS_TOKEN_KEY,
  SP_FACEBOOK_ACCESS_TOKEN_KEY,
  SP_ACCOUNT_TYPE_KEY,
  SP_ACCOUNT_NAME_KEY,
  SP_ACCOUNT_PHONE_KEY,
  SP_ACCOUNT_E_MAIL,

}